### ISSUE TITLE
Crash when checking for updates

### ISSUE THREAD

**Issue by jona339e** [iraizo/duskhaven-loader#15]
Downloaded launcher & set game path to "D:\Duskhaven\World of Warcraft 3.3.5"

Pressed the check for update button, waited a few seconds and it crashed.

[crash.log](https://github.com/iraizo/duskhaven-loader/files/11070389/crash.log)

(My launcher and config.json is in the path "D:\Duskhaven\Launcher"

**Comment by iraizo** [comment]
please download the config.json from https://github.com/iraizo/duskhaven-loader/releases/tag/v0.6.0
