### ISSUE TITLE
Duskhaven Launcher Error

### ISSUE THREAD

**Issue by mmbrown71575** [iraizo/duskhaven-loader#18]
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src/updater.rs:67:18

**Comment by iraizo** [comment]
Disable read only on realmlist.wtf

**Comment by Kiaburn1976** [comment]
I have the same panicked comment but, mine came out differently: panicked at 'index out of bounds: the len is 0 but the index is 0', src/updater.rs:54:50

**Comment by iraizo** [comment]
do you have an enUS folder

**Comment by Kiaburn1976** [comment]
Yes I do.

**Comment by iraizo** [comment]
can you show me what path u set it as and the folder itself?

**Comment by Kiaburn1976** [comment]
Im sorry my folder is named enGB not enUS. The game folder sits on my desktop. Inside the Data folder is the enGB folder.

**Comment by iraizo** [comment]
what is it set to in the settings

**Comment by Kiaburn1976** [comment]
C:\Users\Thugb\OneDrive\Desktop\Private Wow Servers\Duskhaven Vanilla +

I was putting the launcher into the folder where duskhaven is, not inside the folder I made to download the game.

**Comment by iraizo** [comment]
try to change paths
