### ISSUE TITLE
wont start anymore.

### ISSUE THREAD

**Issue by xWrizzla** [iraizo/duskhaven-loader#27]
i know theres a crashlog for the launcher when something bad happens, but since the last launcher update it wont start anymore. so i cant really submit the crashlog because theres none.... just wanted to let you guys know. redownload didnt helped either.

**Comment by iraizo** [comment]
make sure to put the config.json next to it

**Comment by xWrizzla** [comment]
Funny enough, right after this i tried the redownload again, and started it as admin it worked again. so sorry for that. 

if you got the power for that, you can delete this :D 

again, im sorry.

**Comment by iraizo** [comment]
No worries dude!
