### ISSUE TITLE
Extremely Slow Install Speed + Install Crash

### ISSUE THREAD

**Issue by Shiniest-Skritt** [iraizo/duskhaven-loader#28]
I tried installing the client  via launcher. The installation speed would cap at 0.18 mb/s.

Additionally, somewhere around 35% installation, the installation crashed. The crash log is below:

panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) }', src/installer.rs:62:62

**Comment by iraizo** [comment]
This has been fixed now, restart
