### ISSUE TITLE
Launcher doesn't install.

### ISSUE THREAD

**Issue by Kebful** [iraizo/duskhaven-loader#3]
https://gyazo.com/583d2b991ec7f8608d0c2bdefe12b8dd

When pressing Install launcher does not do anything. Status bar says idle.

CMD doesn't show any error messages as well but Update button changes to Updating..

=== CONFIG FILE SHOWS THIS WHEN ATTEMPTING ==

{
  "files": [
    {
      "name": "patch-5.mpq",
      "path": "Data",
      "etag": "rr0psg1kymka",
      "url": "https://duskhaven.raizo.dev/patch-5.mpq"
    },
    {
      "name": "patch-Z.mpq",
      "path": "Data",
      "etag": "rr0q7t1hi8wae",
      "url": "https://duskhaven.raizo.dev/patch-Z.mpq"
    },
    {
      "name": "wow.exe",
      "path": "",
      "etag": "rr0prg4l4m0",
      "url": "https://duskhaven.raizo.dev/wow.exe"
    }
  ],
  "path": "E:\\raizo test client",
  "wow": "https://duskhaven.raizo.dev/wow-3-3-5.zip",
  "realmlist": "set realmlist duskhaven.servegame.com"
}

**Comment by iraizo** [comment]
Fixed
