### ISSUE TITLE
Game file 16gig already

### ISSUE THREAD

**Issue by JayTheProduct** [iraizo/duskhaven-loader#32]
Only at 12% and file named game is already 16gig? It hasnt gotten bigger since 10% so not sure whats going on. I'm not good with this stuff its probably nothing.
![Huge file](https://user-images.githubusercontent.com/128994771/227792073-b4b600a5-cfae-410e-aec0-5962167ac2ce.JPG)

**Comment by iraizo** [comment]
can you remember if you perhaps clicked twice on install?

**Comment by JayTheProduct** [comment]
Yes, I thought I had to because of the launcher itself updating? Should I delete and start over?

**Comment by iraizo** [comment]
> Yes, I thought I had to because of the launcher itself updating? Should I delete and start over?

Yes, never press it twice since it will also do it twice then
