### ISSUE TITLE
Launcher Crash

### ISSUE THREAD

**Issue by Xurkon** [iraizo/duskhaven-loader#7]
Crash log says:

panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src/updater.rs:67:18

Ran it as admin, no reason there should be a permission error. Tried it with and without spaces in the install path, update refuses to work but an install works.

**Comment by iraizo** [comment]
show me the path please

**Comment by killersoxfan** [comment]
![image](https://user-images.githubusercontent.com/128938821/227745422-93525bec-ebcd-479b-897c-adaa109f9362.png)
 halp im stoopid

**Comment by killersoxfan** [comment]
My patch halfway downloaded then crashed and wont start up again
![image](https://user-images.githubusercontent.com/128938821/227745515-38435e5e-0cd3-4323-8589-2b40a324558e.png)

**Comment by emilmajstro** [comment]
> 

this is probably because of the ongoing ddos attack ref #8

**Comment by iraizo** [comment]
Correct

**Comment by killersoxfan** [comment]
thanks :)

**Comment by zsimmons25** [comment]
This is due to realmlist.wtf still being set to read only, @iraizo could you update your Discord announcement to inform people to change it back if they start using the launcher.

**Comment by iraizo** [comment]
Hm you may be correct, yes.

**Comment by Xurkon** [comment]
Path for me is D:\WoWDuskhaven and realmlist has full control

**Comment by iraizo** [comment]
realmlist cant be written to, its read only
