### ISSUE TITLE
Crash log while downloading patch Z and pressing update 

### ISSUE THREAD

**Issue by emilmajstro** [iraizo/duskhaven-loader#8]
updated patch 5, while updating patch Z - press update again and u get this crash log, but the launcher doesn't actually crash and keeps showing it's updating patch Z so idk it still probably works as intended.

panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(88.198.38.70)), port: Some(8443), path: "/patch-5.mpq", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10060, kind: TimedOut, message: "Anslutningsförsöket misslyckades eftersom den anslutna datorn inte svarade inom en viss tid eller på grund av att den etablerade anslutningen till värddatorn inte längre fungerar." })) }', src/updater.rs:77:63

translated message: "The connection attempt failed because the connected computer did not respond within a certain time or because the established connection to the host computer is no longer working."

**Comment by iraizo** [comment]
theres currently a ddos so there may be connection issues

**Comment by iraizo** [comment]
Please update the config.json from https://github.com/iraizo/duskhaven-loader/releases/tag/v0.6.0
